name: Build fpm/php8.1 docker image version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_REPOSITORY: gru.ocir.io/grwidfxfmi4f/app-docker-image
  WEB_SERVER: fpm
  PHP_VERSION: "8.1"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    name: Build docker image - Apache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_LOGIN }}
          password: ${{ secrets.OCI_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./php/
          file: ./php/Dockerfile.${{env.WEB_SERVER}}
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{env.PHP_VERSION}}
          tags: |
            ${{env.IMAGE_REPOSITORY}}:php-${{env.PHP_VERSION}}-${{env.WEB_SERVER}}

      - name: Dump context
        if: always()
        uses: raniellyferreira/ghaction-dump-context@v1
